### ISSUE TITLE
Player does not support ids with underscore

### ISSUE THREAD

**Issue by rolandschuetz** [jonnitto/Jonnitto.PrettyEmbedYoutube#10]
**Describe the bug**
Setting a YouTube Id `_GfQ81ghr5c` does not work.

**Comment by jonnitto** [comment]
Can you open an issue at https://github.com/jonnitto/Jonnitto.PrettyEmbedHelper? The parsing is happening in this package…

**Comment by jonnitto** [comment]
https://github.com/jonnitto/Jonnitto.PrettyEmbedHelper/releases/tag/2.6.4
