### ISSUE TITLE
No sizing of iframe

### ISSUE THREAD

**Issue by SoulCover** [jonnitto/Jonnitto.PrettyEmbedYoutube#3]
On [line 48](https://github.com/jonnitto/Jonnitto.PrettyEmbedYoutube/blob/master/Resources/Private/Javascripts/Main.js#L48) of the JavaScript file `link.childNodes[0]` returns the first childNode, which in this case is plaintext :(

Just Replace l48 and l49 with:
```javascript
var firstImageChild = link.getElementsByTagName('img')[0];
var w = firstImageChild.width;
var h = firstImageChild.height;
```

**Comment by jonnitto** [comment]
Thank you! I've done some JS and CSS Improvements. After some testing I'm gonna release 2.1.0
