### ISSUE TITLE
Player symbol almost invisible

### ISSUE THREAD

**Issue by klfman** [jonnitto/Jonnitto.PrettyEmbedYoutube#8]
It is very hard to see the player-symbol on videos with a bright preview image.
Example:

![Screenshot 2020-03-04 at 13 01 57](https://user-images.githubusercontent.com/9661367/75877667-801f9180-5e18-11ea-9fcb-66fc019b7faf.png)

I would love the included css to grey out the interior of the small arrow, so it's not fully transparent and thus better visible.

**Comment by klfman** [comment]
To clarify: I mean something like this:

```
.jonnitto-prettyembed--iframe:not(.jonnitto-prettyembed--play):not(.jonnitto-prettyembed__content)::after, .jonnitto-prettyembed--video::after {
        background-color: gray;
        border-radius: 72px;
}
```

Plain gray might not be the perfect tone of color in this example but it would help the visibility immensely. I think this helps everyone, so I'm reporting it here (instead of just adapting the css in my project), because bright backgrounds are relatively common in videos.

**Comment by jonnitto** [comment]
Thank you for the report. This more depends to [Jonnitto.PrettyEmbedHelper](https://github.com/Jonnitto/Jonnitto.PrettyEmbedHelper), as there is all the CSS. I plan to release a version with an SVG symbol, like that everyone can adjust it to the required needs

**Comment by jonnitto** [comment]
I'm working on this issue. The buttons will go to look like this:  
![image](https://user-images.githubusercontent.com/4510166/76141593-1ac0e000-6066-11ea-8a1d-344251803a55.png)

**Comment by jonnitto** [comment]
![Youtube - Pretty Embed Series](https://user-images.githubusercontent.com/4510166/76709350-6fb3c480-66fe-11ea-853f-630499f626a2.png)

**Comment by jonnitto** [comment]
So, version [7.0.0](https://github.com/jonnitto/Jonnitto.PrettyEmbedYoutube/releases/tag/7.0.0) with many new features is released! Have fun with it!
